emptyArray: []
collections:
  docs:
    output: true
  amuseum:
    output: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
title: NP-Incompleteness
description: Kunigami's Technical Blog
author: Guilherme Kunigami
